# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Point
version:      0.05
version_from: 
installdirs:  site
requires:
    Geo::Distance:                 0.06
    Geo::Proj4:                    0.96
    Math::Polygon:                 0.003
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
